### ISSUE TITLE
Changing Bomb Blink crash

### ISSUE THREAD

**Issue by Hekumoi** [joao7yt/CSHUE#1]
When I'am trying to open bomb blink option app crashes. I would be nice to get bedroom lights off. All the rest works nice :)

**Comment by joao7yt** [comment]
How many lights do you own?

**Comment by Hekumoi** [comment]
16 lights..... :)

**Comment by joao7yt** [comment]
Ok, I just own 1, so must be something related to multiple lights... I will figure out how to test it out...

Do you know if any other lights setting is bugged as well?

Another thing: it would be cool if you sent a screenshot of how the button's gradient look like with different colors selected for each light in one of the configs :) I just tested it faking lights, but couldn’t test it using true lights, so I don’t know if it truly works...

**Comment by Hekumoi** [comment]
I was able to change all the rest but just this blinking is crashing. When I press one time it reload a while and then just crashing, no any text.

**Comment by Hekumoi** [comment]
Update: I can choose just one light. If I choose more, the hole thing wont work. I can choose one light all of the options except blinking bomb which still crashes.

**Comment by joao7yt** [comment]
It’s intended.

When sending commands too close in time one from another for more than one light, the delays change inconsistently, messing with the sync between the blinks... unfortunately there’s nothing much I can do about it...

P.S.: but wait, how could you open the Blink setting? Wasn’t it crashing before?

**Comment by Hekumoi** [comment]
I can't open blink setting. It still crashes If I'am trying to open it.

**Comment by joao7yt** [comment]
Oh, so you can only select one light in every light setting? If so, it’s something very bad... I will check it today

**Comment by joao7yt** [comment]
I'm struggling narrowing it down. I wasn't able to reproduce it by faking more lights...

I tried some changes, can you pls test the version attached? (If it prompts you about a new version, just ignore the message...)
[CSHUE-test.version.zip](https://github.com/joao7yt/CSHUE/files/3243418/CSHUE-test.version.zip)

**Comment by Hekumoi** [comment]
Yeah. Now blinking option is working. As you said earlier you can only choose one light to use in game. Unfortunately app decide what lamp I have to use. I want to change kitchen table lamp to PC lightstrip and take all the rest off but unfortunately this isn't working right now.

**Comment by joao7yt** [comment]
You can only use 1 light in the blink option, all the other options you should be able to select how many you may... What does exactly happen when you select more than 1?

**Comment by Hekumoi** [comment]
App always take my kitchen table lamp no matter what I choose.

**Comment by joao7yt** [comment]
So, let’s talk about a specific event here, so I can understand exactly where’s the problem:

Let’s take the Main Menu event... answer me some questions:

1. Click to open its setting.
a. does it open?
b. are you able to checkmark more than one light?
c. are lights physically changing states as you check them, change their brightness, or change their color?

2. After changing its setting, open CS:GO.
a. are lights correctly being set to their states select on your settings?

**Comment by Hekumoi** [comment]
Click to open its setting.
a. does it open? YES
b. are you able to checkmark more than one light? YES
c. are lights physically changing states as you check them, change their brightness, or change their color? YES

After changing its setting, open CS:GO.
a. are lights correctly being set to their states select on your settings? NO
If I take 4 lights, it only takes one light and randomly takes color if I choose 4 different light when I start the game.

+
I can choose at least one strip and 2 bulbs, but no 2 stripes in main menu option.
Others aren't upgrading at all or it crashes and might changes after app reboot.
App isn't stable at all if there is more than one light.
No matter what lamp I choose, one light (in my case kitchen table light) is always included
I can only use one light in game and it's kitchen table light

**Comment by joao7yt** [comment]
I'm trying to figure it out... could we exchange contacts so we can talk better? steam, discord...

**Comment by Hekumoi** [comment]
Yeah. Hekumoi in both apps.

**Comment by joao7yt** [comment]
Ok, added

**Comment by joao7yt** [comment]
There's a new release: https://github.com/joao7yt/CSHUE/releases/tag/2019.162.1106.5

Let me know if it's fixed or not yet.

P.S.: I also optimized the light selector, see if it will fix the blinking lights when selecting their colors.

**Comment by Hekumoi** [comment]
Bomb is not blinking, if I'm trying to choose lamp what I want. If I choose the lamp that I want color goes black in the app. I have to take light what program decide (kitchen light in my case). Otherwise everything is working. Great job!

**Comment by joao7yt** [comment]
Now it's fixed. In the next release it will take effect
