### ISSUE TITLE
Won't find bridge

### ISSUE THREAD

**Issue by confusion12345** [joao7yt/CSHUE#10]
Trying to run the program for the first time.

Hue Bridge is not found, the search doesn't seem to take very long before it says 

"The selected Philips Hue Bridge is no longer reachable ..."

Razer Synapse had issues finding my bridge too but I was able to put in my Hue Bridge's IP address and then it worked.

Can something similar be done here?

**Comment by joao7yt** [comment]
I will take notice about it. Maybe it will need me to implement this feature.

**Comment by confusion12345** [comment]
Update:  I just launched the app again (to try and get more info on what was happening) and this time it found the Hue Bridge on its own (Didn't need to search). 

I must have pressed the "Search" button close to 100 times earlier and kept getting the above error.  Only thing that has happened since then is that I restarted my pc.

¯\_(ツ)_/¯

**Comment by joao7yt** [comment]
thats good to hear

**Comment by simenah** [comment]
This happened to me aswell. Wouldnt work after installing. Read this issue, and restarted my pc - but still didnt work for me. Went back to work for a few hours, then went back here to create a new issue regarding this. When I launched the app to find the exact error, it suddenly worked. No idea if this helps in any way @joao7yt :)
