### ISSUE TITLE
Add option to change port

### ISSUE THREAD

**Issue by Kordonme** [joao7yt/CSHUE#11]
As a developer myself, I'm pretty annoyed that this tool uses port 3000 as I run a lot of dev apps on the same port on a regular basis.

**Comment by joao7yt** [comment]
I will mark this as a feature request to add an option in settings where you can change the port.

**Comment by Kordonme** [comment]
Do you accept PR's?

**Comment by joao7yt** [comment]
sure, feel free to

**Comment by joao7yt** [comment]
latest version has this option in settings
