### ISSUE TITLE
Trojan file

### ISSUE THREAD

**Issue by Carlson02** [joao7yt/CSHUE#13]
So i have this issue where my pc sais there is a trojan file inside of the zip, and no matter what i do it will not accept it.
Do you know why there is a trojan file or how to fix it?

**Comment by joao7yt** [comment]
so, I don't have a digital signature... that's something I would need to renovate yearly and as this is a free software, I don't make any money from this, so the .exe file is unsigned.

that's why it says there's something suspicious about it in the zip.

now, it could be your third party anti virus, or windows defender... in any case, you will need to trust the .zip and probably also the .exe inside it after you unzip it...

**Comment by Carlson02** [comment]
Oh ok, but why is there 3 files named something with trojan

**Comment by joao7yt** [comment]
which files?

**Comment by Carlson02** [comment]
the main file

**Comment by joao7yt** [comment]
you said there are 3 files being accessed to be Trojans... which are those 3?

I think only the .exe should be accused

**Comment by Carlson02** [comment]
idk it just gave me three warnings from a folder or something within the CSHUE files

**Comment by Carlson02** [comment]
With Trojen as the warning on all three files

**Comment by Carlson02** [comment]
Yeah the name is Trojan:Script/wacatac.B1ml

**Comment by joao7yt** [comment]
I just downloaded the .zip file I uploaded earlier there on the release and it also accused viruses while the original .zip file I still had on my machine is still fine. I don't know what happened there, but now I reuploaded the same .zip and now it didn't accuse viruses. try it again

**Comment by Carlson02** [comment]
Everything works fine now

**Comment by Carlson02** [comment]
Now i just have the problem with the program just not doing anything, it sais that its connected to my bridge and stuff. But it dosent do anything in game :/

**Comment by joao7yt** [comment]
check if there's a warning in the CS:GO GSI tab. in the last update I changed the port that GSI will use. Try going in that tab and creating the file again

**Comment by Carlson02** [comment]
Its sais something about "This program cannot be run in DOS mode."

**Comment by joao7yt** [comment]
check if everything is fine with this last version I just released.
