### ISSUE TITLE
Crash report. UTC: 2019/10/15 20:43:59

### ISSUE THREAD

**Issue by Johnson0993** [joao7yt/CSHUE#2]
I can't change any color. When I try too, and then I save my changes, the app crashes.
[log-2019_10_15_20_43_59.log](https://github.com/joao7yt/CSHUE/files/3731383/log-2019_10_15_20_43_59.log)

```
HResult:    -2147467261
HelpLink:   
Message:    Object reference not set to an instance of an object.
Source:     CSHUE
```

**Comment by joao7yt** [comment]
i will investigate it... let's see if the crash log feature will help solving it. thanks

**Comment by Johnson0993** [comment]
Many thanks for the (very) quick response!

**Comment by joao7yt** [comment]
So, you are able to choose the colors but when you click "Ok" on the "Light Selector" window it crashes?

**Comment by Johnson0993** [comment]
Yes. First of all, when I open CSHUE and I go to Settings, all the colors by default are black. Like in the Screen 1. I don't know if it's normal. Then, when I click on the black rectangle, I see this (Screen 2).
I can select lights and adjust colors, but when I click "Ok" on the bottom right in the Light Selector window, it crashes, indeed.

![Screen 1](https://user-images.githubusercontent.com/56610447/66869623-13f2dd00-efa0-11e9-9590-45172ff1b8fa.jpg)
![Screen 2](https://user-images.githubusercontent.com/56610447/66869687-2a009d80-efa0-11e9-83c5-96d54f00f6ee.png)

**Comment by joao7yt** [comment]
Hmm interesting... something I noticed: all of your light are unchecked... have you tried selecting at least one before clicking “Ok”?

**Comment by Johnson0993** [comment]
Yes I tried, it crashes either if I check one or many, or if I don't check any.

**Comment by joao7yt** [comment]
What version are you in? (Reminder to me: add version number to the crash logs)

**Comment by Johnson0993** [comment]
I'm using the v2019.249.117.57 :)

**Comment by joao7yt** [comment]
Ok, after college i will try to solve this. Thank you.

**Comment by Johnson0993** [comment]
Thank you really much!

**Comment by joao7yt** [comment]
So, I was not able to reproduce the issue... Do you have any knowledge about coding? Because I would like to, perhaps, start a call with you on discord and giving you instructions on how to debug my program, because on my machine it does not happen...

**Comment by Johnson0993** [comment]
Unfortunately I do not. If you tell me what to do step by step I surely can do that, I already done that, but I can't take any initiative because my skills in coding are very low.

**Comment by Johnson0993** [comment]
Also my english is quite bad.

**Comment by joao7yt** [comment]
I can tell you what to do... or if you are fine with teamviwer I can even do it myself while you watch hahaha do you have discord?
