### ISSUE TITLE
Crash report. UTC: 2019-12-11 14:17:12

### ISSUE THREAD

**Issue by DJMogens** [joao7yt/CSHUE#4]
(Extra information here)
```
Version:    2019.310.1304.11
HResult:    -2146233087
HelpLink:   
Message:    Aktiveringen af konstruktøren på typen 'CSHUE.Views.MainWindow', som svarer til de angivne bindingsbegrænsninger, udløste en undtagelse.
Source:     PresentationFramework

	HResult:    -2146232062
	HelpLink:   
	Message:    Konfigurationssystemet kunne ikke initialiseres
	Source:     System.Configuration

		HResult:    -2146232062
		HelpLink:   
		Message:    '.', den hexadecimale værdi 0x00 er et ugyldigt tegn. linje 17, position 1. (C:\Users\Xtrme rig Dani788c\AppData\Local\CSHUE\CSHUE.exe_Url_0idcgiyyipsmsvariq4pybhtuki5booe\1.0.0.0\user.config line 17)
		Source:     System.Configuration

			HResult:    -2146232000
			HelpLink:   
			Message:    '.', den hexadecimale værdi 0x00 er et ugyldigt tegn. linje 17, position 1.
			Source:     System.Xml
```

**Comment by joao7yt** [comment]
Can you provide some extra information on when this happens? Or include the log file created

**Comment by DJMogens** [comment]
[log-2019_12_12_16_30_45.log](https://github.com/joao7yt/CSHUE/files/3956824/log-2019_12_12_16_30_45.log)
[log-2019_12_11_15_27_02.log](https://github.com/joao7yt/CSHUE/files/3956825/log-2019_12_11_15_27_02.log)
[log-2019_12_11_15_27_15.log](https://github.com/joao7yt/CSHUE/files/3956826/log-2019_12_11_15_27_15.log)

**Comment by DJMogens** [comment]
happens every time it tries to open

**Comment by joao7yt** [comment]
Please, send to me the “C:\Users\Xtrme rig Dani788c\AppData\Local\CSHUE\CSHUE.exe_Url_0idcgiyyipsmsvariq4pybhtuki5booe\1.0.0.0\user.config” file, it’s is saying there’s something wrong with it... I want to take a look at it.

After sending it, try deleting the “C:\Users\Xtrme rig Dani788c\AppData\Local\CSHUE\” folder and run the app again.

**Comment by DJMogens** [comment]
[user.zip](https://github.com/joao7yt/CSHUE/files/3956933/user.zip)

**Comment by DJMogens** [comment]
After deleting: worked like a charm

**Comment by joao7yt** [comment]
Something messed up with your .config file, idk why that happened... Did you just downloaded CSHUE and run it and that happens? Or did you already used CSHUE before?

**Comment by DJMogens** [comment]
It worked fine. Just one day at startup that happened. Only thing new is
update to csgo

tor. 12. dec. 2019 18.47 skrev João Mambelli <notifications@github.com>:
