### ISSUE TITLE
CSHUE Wont open

### ISSUE THREAD

**Issue by dodson02** [joao7yt/CSHUE#6]
Sorry im not that techy, CSHUE wont open to the screen like the video

**Comment by joao7yt** [comment]
hey, what system are you using?

**Comment by dodson02** [comment]
i truly appreciate the quick response, im using windows

**Comment by dodson02** [comment]
i have WINRAR downloaded if that helps

**Comment by joao7yt** [comment]
did you try to run "CSHUE.exe"?

**Comment by dodson02** [comment]
it opened, ill try and do this myself, hopefully i can do this. Thanks! ill message again if i need help. You got discord?

**Comment by joao7yt** [comment]
sure, john#1602

**Comment by dodson02** [comment]
just added ur discord
