### ISSUE TITLE
doesent work

### ISSUE THREAD

**Issue by nkls089** [joao7yt/CSHUE#8]
Good evening,
I have a problem with the application CSHUE. It doesent work on my pc and I dont know why.
The program automatically creates the .cfg file under D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive. But in the video I saw the file path 
![Unbenannt](https://user-images.githubusercontent.com/65566128/82254397-0eed7600-9953-11ea-95fc-e8a867df1503.PNG)
was different. Is that a reason?
Or do I have to turn something off in the Phillips Hue Sync app?

Thank you in advance

**Comment by joao7yt** [comment]
It’s the wrong folder... are you sure it created automatically the file? Or did you have to manually select the folder?

**Comment by nkls089** [comment]
First I manually selected the folder but then I saw that it could be the wrong one. After that I couldn‘t change it anymore. I deleted the program several times but the program automatially creates the file in this file path. I don‘t know how to change it now.Gesendet mit der WEB.DE iPhone AppAm 18.05.20 um 22:02 schrieb João Mambelli
            
        
        
            
                Von: "João Mambelli" <notifications@github.com>Datum: 18. Mai 2020An: joao7yt/CSHUE <CSHUE@noreply.github.com>Cc: nkls089 <niklasberlinger@web.de>,Author <author@noreply.github.com>Betreff: Re: [joao7yt/CSHUE] doesent work (#8)
            
            

Itâs the wrong folder... are you sure it created automatically the file? Or did you have to manually select the folder?



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/joao7yt/CSHUE/issues/8#issuecomment-630406045",

"url": "https://github.com/joao7yt/CSHUE/issues/8#issuecomment-630406045",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by joao7yt** [comment]
Try resetting to default settings in the app settings

**Comment by nkls089** [comment]
I did it and the file path should be correct now but unfortunately it still doesent work :(

 
 

Gesendet: Montag, 18. Mai 2020 um 22:39 Uhr
Von: "João Mambelli" <notifications@github.com>
An: "joao7yt/CSHUE" <CSHUE@noreply.github.com>
Cc: "nkls089" <niklasberlinger@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [joao7yt/CSHUE] doesent work (#8)


 

Try resetting to default settings in the app settings

**Comment by joao7yt** [comment]
What appears on home? And what was the path? csgo/cfg/?

**Comment by nkls089** [comment]
I send you pictures what I see on my home and the path.
 

Gesendet: Montag, 18. Mai 2020 um 23:19 Uhr
Von: "João Mambelli" <notifications@github.com>
An: "joao7yt/CSHUE" <CSHUE@noreply.github.com>
Cc: "nkls089" <niklasberlinger@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [joao7yt/CSHUE] doesent work (#8)


 

What appears on home? And what was the path? csgo/cfg/?

**Comment by joao7yt** [comment]
what is your discord or steam?
