### ISSUE TITLE
How do i open the app?

### ISSUE THREAD

**Issue by CalZ90** [joao7yt/CSHUE#9]
Hello, nice program. Seen a danish streamer use it. 

I have downloaded it, but how to i open it?

**Comment by CalZ90** [comment]
I cant locate it. 

I have a cshue sln-file and a cshue.sln dot.settings-file?

**Comment by joao7yt** [comment]
Oh, you have downloaded the wrong file. Go to the “Code” tab, then a bit down you will see the “Releases” tab, containing 12 releases. Click that. Then on the last release you will see the “CSHUE-<version>.zip”. Download it and you are done.

**Comment by CalZ90** [comment]
Ah perfect ! It works ! love it !

**Comment by joao7yt** [comment]
Thank you!
